from flask import Flask, request, jsonify
from flask_cors import CORS
import joblib
import pandas as pd
import os
import sqlite3
import time
import json

from advanced_model import train_model, predict
import joblib

app = Flask(__name__)
CORS(app)  # Allow frontend to access this API

MODEL_PATH = 'revenue_model.pkl'
FEATURES_PATH = 'model_features.pkl'

# Load the trained model and features
model = None
features = []

def format_inr_text(value):
    if value >= 10000000:
        return f"₹{value/10000000:.2f} Crores"
    elif value >= 100000:
        return f"₹{value/100000:.2f} Lakhs"
    else:
        # standard fallback
        s = str(int(value))
        if len(s) <= 3:
            return f"₹{s}"
        
        last_three = s[-3:]
        remaining = s[:-3]
        chunks = []
        while len(remaining) > 0:
            chunks.insert(0, remaining[-2:])
            remaining = remaining[:-2]
        formatted = ",".join(chunks) + "," + last_three
        formatted = ",".join(chunks) + "," + last_three
        return f"₹{formatted}"

def init_db():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS Messages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                sender_role TEXT NOT NULL,
                receiver_role TEXT NOT NULL,
                message TEXT NOT NULL,
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                is_read INTEGER DEFAULT 0
            )
        ''')
        conn.commit()
    except Exception as e:
        print(f"DB Init Error: {e}")
    finally:
        if 'conn' in locals():
            conn.close()

init_db()

if os.path.exists(MODEL_PATH) and os.path.exists(FEATURES_PATH):
    model = joblib.load(MODEL_PATH)
    features = joblib.load(FEATURES_PATH)
    print("Model and features loaded successfully.")
else:
    print("Warning: Model files not found. Please train the model first.")

@app.route('/api/predict', methods=['POST'])
def predict_revenue():
    if not model:
        return jsonify({'error': 'Model not trained or loaded.'}), 500

    try:
        data = request.json
        # Create a DataFrame from incoming data ensuring all expected features exist
        input_data = {}
        for feature in features:
            input_data[feature] = data.get(feature, 0) # default to 0 if missing

        df = pd.DataFrame([input_data])
        prediction = model.predict(df)
        
        return jsonify({
            'predicted_revenue': round(prediction[0], 2),
            'status': 'success'
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 400

@app.route('/api/status', methods=['GET'])
def status():
    return jsonify({'status': 'Backend API is running', 'model_loaded': model is not None})

@app.route('/', methods=['GET'])
def home():
    return jsonify({
        'message': 'Welcome to the SmartDashboard ML Backend API!',
        'status': 'Running',
        'predict_endpoint': 'POST /api/predict',
        'health_check': 'GET /api/status'
    })

def generate_insights():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        
        # Insight 1: Top Product
        cursor.execute("SELECT Product, SUM(Net_Profit) as total_profit FROM Business_Data GROUP BY Product ORDER BY total_profit DESC LIMIT 1")
        top_product = cursor.fetchone()
        
        # Insight 2: Underperforming Region
        cursor.execute("SELECT Region, SUM(Revenue) as total_revenue FROM Business_Data GROUP BY Region ORDER BY total_revenue ASC LIMIT 1")
        bottom_region = cursor.fetchone()

        # Insight 3: High Loss Reason
        cursor.execute("SELECT Loss_Reason, COUNT(*) as count FROM Business_Data WHERE Loss_Reason != 'None' AND Loss_Reason IS NOT NULL GROUP BY Loss_Reason ORDER BY count DESC LIMIT 1")
        top_loss = cursor.fetchone()

        insights = []
        if top_product:
            insights.append({
                "icon": "📈", 
                "title": "Top Performer", 
                "text": f"Highest profit generated by {top_product[0]} ({format_inr_text(top_product[1])}).",
                "type": "positive"
            })
        if bottom_region:
            insights.append({
                "icon": "⚠️", 
                "title": "Needs Attention", 
                "text": f"{bottom_region[0]} region has the lowest revenue ({format_inr_text(bottom_region[1])}).",
                "type": "negative"
            })
        if top_loss:
            insights.append({
                "icon": "💡", 
                "title": "Operational Insight", 
                "text": f"Most common reason for loss: {top_loss[0]}.",
                "type": "info"
            })
        
        # Fallback if DB is empty
        if not insights:
            insights = [{"icon": "📊", "title": "Data Required", "text": "Upload more data to see insights.", "type": "info"}]
            
        return insights
    except Exception as e:
        print(f"Error generating insights: {e}")
        return [{"icon": "❌", "title": "Error", "text": "Failed to generate insights.", "type": "negative"}]
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/insights', methods=['GET'])
def get_insights():
    insights = generate_insights()
    return jsonify(insights)

@app.route('/api/send-message', methods=['POST'])
def send_message():
    try:
        data = request.json
        sender_role = data.get('sender_role')
        receiver_role = data.get('receiver_role')
        message = data.get('message')
        
        if not sender_role or not receiver_role or not message:
            return jsonify({"error": "Missing parameters"}), 400
            
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        cursor.execute('''
            INSERT INTO Messages (sender_role, receiver_role, message) 
            VALUES (?, ?, ?)
        ''', (sender_role, receiver_role, message))
        conn.commit()
        return jsonify({"status": "Message sent"})
    except Exception as e:
        print(f"Send message error: {e}")
        return jsonify({"error": "Failed to send message"}), 500
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/get-messages', methods=['GET'])
def get_messages():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        cursor.execute("SELECT id, sender_role, receiver_role, message, timestamp FROM Messages ORDER BY timestamp ASC")
        rows = cursor.fetchall()
        msgs = [{"id": r[0], "sender_role": r[1], "receiver_role": r[2], "message": r[3], "timestamp": r[4]} for r in rows]
        return jsonify(msgs)
    except Exception as e:
        print(f"Error fetching messages: {e}")
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/upload', methods=['POST'])
def upload_file():
    try:
        if 'csv' not in request.files:
            return jsonify({"error": "No file uploaded. Please select a CSV file."}), 400
            
        file = request.files['csv']
        if not file.filename.endswith('.csv'):
            return jsonify({"error": "Invalid file type. Please upload a valid .csv file"}), 400

        sender_role = request.form.get('role', 'analyst')
        user_id = 1 if sender_role == 'analyst' else 2 # Mocking DB ID
        
        # Save file format
        uploads_dir = os.path.join('..', 'public', 'uploads')
        os.makedirs(uploads_dir, exist_ok=True)
        filename = f"{int(time.time())}_{file.filename}"
        filepath = os.path.join(uploads_dir, filename)
        file.save(filepath)

        # 1. READ CSV (Pandas)
        df = pd.read_csv(filepath)

        # 2. TRAIN MODEL DYNAMICALLY
        try:
            model, accuracy, top_features = train_model(df, target_col="Revenue")
        except Exception as ml_err:
            return jsonify({"error": f"ML Training Error: Ensure dataset has 'Revenue' target column. ({str(ml_err)})"}), 400

        # 3. PREDICT (Using last row as sample future)
        # Drop the target to use the rest of the dataframe structure
        sample_df = df.copy()
        if 'Date' in sample_df.columns:
            sample_df['Date'] = pd.to_datetime(sample_df['Date'])
            sample_df['Month'] = sample_df['Date'].dt.month
            sample_df['Year'] = sample_df['Date'].dt.year
            sample_df = sample_df.drop('Date', axis=1)
            
        sample_df = sample_df.dropna(subset=['Revenue'])
        sample_df = pd.get_dummies(sample_df, drop_first=True)
        sample_x = sample_df.drop("Revenue", axis=1).iloc[-1:]
        
        predicted_val = predict(model, sample_x)[0]
        
        # Determine trend vs last actual row
        last_actual = df['Revenue'].dropna().iloc[-1]
        trend = "upward" if predicted_val > last_actual else "downward"

        # 4. DATABASE INSERTIONS
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        
        cursor.execute("INSERT INTO uploaded_data (user_id, file_name, file_path) VALUES (?, ?, ?)", 
                      (user_id, filename, f"/uploads/{filename}"))
        upload_id = cursor.lastrowid
        
        result_json = {
            "trend": trend,
            "confidence": f"{accuracy * 100:.1f}%",
            "forecast_next_period": f"₹{predicted_val:,.2f}",
            "top_features": top_features,
            "model_used": "RandomForestRegressor"
        }
        
        cursor.execute("INSERT INTO ml_predictions (user_id, upload_id, result) VALUES (?, ?, ?)",
                      (user_id, upload_id, json.dumps(result_json)))
                      
        # Notifications
        cursor.execute("INSERT INTO notifications (user_id, message) VALUES (?, ?)", 
                      (user_id, f"📊 ML Prediction complete! Trend: {trend}, Accuracy: {accuracy*100:.1f}%"))
        
        cursor.execute("SELECT id FROM users WHERE role = 'admin' LIMIT 1")
        admin = cursor.fetchone()
        if admin:
            cursor.execute("INSERT INTO notifications (user_id, message) VALUES (?, ?)", 
                          (admin[0], f"📥 New data uploaded: {file.filename} (Trained dynamically)"))
                          
        conn.commit()
        
        return jsonify({
            "success": True,
            "message": "ML processed successfully",
            "prediction": f"₹{predicted_val:,.2f}",
            "accuracy": round(accuracy, 4),
            "top_features": top_features,
            "trend": trend
        })

    except Exception as e:
        print(f"Upload error: {e}")
        return jsonify({"error": str(e)}), 500
    finally:
        if 'conn' in locals():
            conn.close()

# ── RECHARTS LIVE DATA API ─────────────────────────────────

@app.route('/api/sales-trend', methods=['GET'])
def get_sales_trend():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # Group by Month/Year and SUM Revenue and Profit
        # We assume Date is formatted 'YYYY-MM-DD' or similar
        query = """
        SELECT strftime('%m', Date) as month_num,
               SUM(Revenue) as revenue,
               SUM(Profit) as profit
        FROM Business_Data
        WHERE Date IS NOT NULL
        GROUP BY month_num
        ORDER BY month_num ASC
        """
        cursor.execute(query)
        rows = cursor.fetchall()
        
        month_map = {'01':'Jan', '02':'Feb', '03':'Mar', '04':'Apr', 
                     '05':'May', '06':'Jun', '07':'Jul', '08':'Aug',
                     '09':'Sep', '10':'Oct', '11':'Nov', '12':'Dec'}
                     
        data = []
        for r in rows:
            if r['month_num'] in month_map:
                data.append({
                    "month": month_map[r['month_num']],
                    "revenue": round(r['revenue'] or 0, 2),
                    "profit": round(r['profit'] or 0, 2)
                })
                
        return jsonify(data)
    except Exception as e:
        print(f"Error in sales-trend: {e}")
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/category-distribution', methods=['GET'])
def get_category_distribution():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        cursor.execute("""
        SELECT Product as name, SUM(Revenue) as value
        FROM Business_Data
        GROUP BY Product
        ORDER BY value DESC
        """)
        
        rows = cursor.fetchall()
        data = [{"name": r['name'], "value": round(r['value'] or 0, 2)} for r in rows if r['name']]
        
        return jsonify(data)
    except Exception as e:
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/revenue-by-region', methods=['GET'])
def get_revenue_by_region():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # 1. Get exact total revenue per region
        cursor.execute("""
        SELECT Region as region, SUM(Revenue) as revenue
        FROM Business_Data
        GROUP BY Region
        ORDER BY revenue DESC
        """)
        region_rows = cursor.fetchall()
        
        # 2. Get breakdown subData per Product per Region
        cursor.execute("""
        SELECT Region, Product, SUM(Revenue) as rev
        FROM Business_Data
        GROUP BY Region, Product
        """)
        breakdown_rows = cursor.fetchall()
        
        # Build nested object
        results = []
        for r in region_rows:
            region_name = r['region']
            sub_data = []
            for b in breakdown_rows:
                if b['Region'] == region_name:
                    sub_data.append({
                        "name": b['Product'],
                        "rev": round(b['rev'] or 0, 2)
                    })
            results.append({
                "region": region_name,
                "revenue": round(r['revenue'] or 0, 2),
                "subData": sorted(sub_data, key=lambda x: x['rev'], reverse=True)
            })
            
        return jsonify(results)
    except Exception as e:
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/predictions', methods=['GET'])
def get_recent_predictions():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        cursor.execute("""
        SELECT m.id, m.created_at, m.result, u.file_name
        FROM ml_predictions m
        LEFT JOIN uploaded_data u ON m.upload_id = u.id
        ORDER BY m.created_at DESC
        LIMIT 5
        """)
        
        rows = cursor.fetchall()
        data = []
        for r in rows:
            # Safely parse the JSON result column
            try:
                res = json.loads(r['result'])
            except:
                res = {}
                
            data.append({
                "id": r['id'],
                "created_at": r['created_at'],
                "file_name": r['file_name'] or "Unknown Dataset",
                "result": res
            })
            
        return jsonify(data)
    except Exception as e:
        print(f"Error fetching predictions: {e}")
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

# ── NOTIFICATIONS ──────────────────────────────────────


@app.route('/api/get-new-messages', methods=['GET'])
def get_new_messages():
    try:
        role = request.args.get('role')
        if not role:
            return jsonify([])
            
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        
        # Get unread messages
        cursor.execute("SELECT id, sender_role, message, timestamp FROM Messages WHERE receiver_role = ? AND is_read = 0", (role,))
        rows = cursor.fetchall()
        
        if len(rows) > 0:
            # Mark them as read
            ids = [r[0] for r in rows]
            cursor.execute(f"UPDATE Messages SET is_read = 1 WHERE id IN ({','.join(['?']*len(ids))})", ids)
            conn.commit()
            
        msgs = [{"id": r[0], "sender_role": r[1], "message": r[2], "timestamp": r[3]} for r in rows]
        return jsonify(msgs)
    except Exception as e:
        print(f"Error fetching new messages: {e}")
        return jsonify([])
    finally:
        if 'conn' in locals():
            conn.close()

def check_alerts():
    try:
        conn = sqlite3.connect('../business_analytics.db')
        cursor = conn.cursor()
        alerts = []
        
        # Condition 1: High sales spike
        cursor.execute("SELECT Product, SUM(Units_Sold) FROM Business_Data GROUP BY Product ORDER BY SUM(Units_Sold) DESC LIMIT 1")
        top_sales = cursor.fetchone()
        if top_sales and top_sales[1] > 1000:
            alerts.append({"id": 1, "message": f"High sales spike detected for {top_sales[0]} ({top_sales[1]} units)!", "type": "critical"})
            
        # Condition 2: Revenue drop (we use Profit_Status or Loss as a proxy)
        cursor.execute("SELECT Product, SUM(Loss) FROM Business_Data WHERE Loss > 0 GROUP BY Product ORDER BY SUM(Loss) DESC LIMIT 1")
        high_loss = cursor.fetchone()
        if high_loss and high_loss[1] > 10000:
            alerts.append({"id": 2, "message": f"Critical revenue loss detected in {high_loss[0]} ({format_inr_text(high_loss[1])} lost).", "type": "critical"})
            
        # Standard notification
        cursor.execute("SELECT COUNT(*) FROM Business_Data")
        count = cursor.fetchone()[0]
        alerts.append({"id": 3, "message": f"System active tracking {count} records.", "type": "info"})
        
        return alerts
    except Exception as e:
        print(f"Alerts error: {e}")
        return []
    finally:
        if 'conn' in locals():
            conn.close()

@app.route('/api/notifications', methods=['GET'])
def get_notifications():
    alerts = check_alerts()
    return jsonify(alerts)

@app.route('/api/download-report', methods=['GET'])
def download_report():
    import io
    from flask import send_file
    try:
        conn = sqlite3.connect('../business_analytics.db')
        df = pd.read_sql_query("SELECT * FROM Business_Data", conn)
        csv_data = df.to_csv(index=False)
        
        return send_file(
            io.BytesIO(csv_data.encode()),
            mimetype="text/csv",
            as_attachment=True,
            download_name="smart_business_report.csv"
        )
    except Exception as e:
        print(f"Error downloading report: {e}")
        return jsonify({"error": "Failed to generate report"}), 500
    finally:
        if 'conn' in locals():
            conn.close()

if __name__ == '__main__':
    print("Starting Flask API Server on port 5001...")
    app.run(debug=True, port=5001)
